name: Build & Deploy

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  workflow_dispatch:

env:
  PROJECT_ID: project-b0677df0-7b67-4302-a4a
  REGION: asia-south1
  REPO_API: lifeguard-readmission-api
  REPO_UI: lifeguard-readmission-frontend

jobs:
  build:
    name: Container builds
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/gh-deploy/providers/github
      - name: Build & push API
        uses: google-github-actions/build-push-images@v0
        with:
          path: backend
          repository: gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_API }}
          tags: ${{ github.ref_name }}-${{ github.sha }}
      - name: Build & push frontend
        uses: google-github-actions/build-push-images@v0
        with:
          path: frontend
          repository: gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_UI }}
          tags: ${{ github.ref_name }}-${{ github.sha }}

  deploy-dev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/gh-deploy/providers/github
      - working-directory: infra/environments/dev
        run: terraform init -input=false
      - working-directory: infra/environments/dev
        run: terraform apply -auto-approve -var "api_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_API }}:${{ github.ref_name }}-${{ github.sha }}" -var "frontend_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_UI }}:${{ github.ref_name }}-${{ github.sha }}"

  deploy-prod:
    name: Deploy to prod
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    environment: production
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_ID }}/locations/global/workloadIdentityPools/gh-deploy/providers/github
      - working-directory: infra/environments/prod
        run: terraform init -input=false
      - working-directory: infra/environments/prod
        run: terraform apply -auto-approve -var "api_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_API }}:${{ github.ref_name }}-${{ github.sha }}" -var "frontend_image=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_UI }}:${{ github.ref_name }}-${{ github.sha }}"
